Manthan933/Manthan

- server/models/classrooms.model.js
> Fixed issue "Unable to create a class"

- client/src/components/Froms/QuestionForm.js
bug fixed 
bug description :  #12  
whenever user try to add question without any content error message will display at bottom
> Fixed issue "Questions with no content/options can be added "

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
> Updated readme

- client/src/components/Froms/CreateTest.js
Bug description : #21 
If teacher try to create test without providing test name and marks then error message will dispaly at bottom.
> bug fixed : "Teacher can create test without providing test name and marks" 

- docker-compose.yml
- server/Dockerfile
- server/controllers/classrooms.js
> Docker setup for development 

- client/src/views/classroom/Classroom.js
> Class Code visible only for instructor

- .github/config.yml
Added the GitHub action as a welcome bot.
> welcome bot added

- README.md
Added Dynamic Contributors images to repo
Fix: https://github.com/Manthan933/Manthan/issues/32
> Added Dynamic Contributors images to repo

- client/src/components/Froms/CreateTest.js
- client/src/components/Froms/Review.js
- client/src/components/Froms/TestForm.js
Fixed Duration Box bug, Duration should be in hours/minutes
Used separate states to avoid below issue
a-component-is-changing-an-uncontrolled-input-of-type-text-to-be-controlled-error
> #29 Numeric Duration Box

- client/src/actions/actions.js
- client/src/api/api.js
- client/src/views/classroom/Classroom.js
- server/controllers/classrooms.js
#8 Option to remove student from classroom - UI flow created
> #8 Added Option to remove student

- client/src/actions/actions.js
- client/src/api/api.js
- client/src/components/ClassCard/ClassCard.js
- client/src/components/Froms/CreateClass.js
- client/src/components/Froms/CreateTest.js
- client/src/components/Froms/Review.js
- client/src/components/Froms/TestForm.js
- client/src/views/main/Main.js
- server/controllers/classrooms.js
- server/routes/classrooms.js
#36 Joining Class creating temp. duplicate instance for same class - This is fixed.
Problem Details:
After joining, email is getting added to classroom for added users. This will result in updated data set.
This updated data set was getting added on every new user joining. Fixed by proper handling of updated data set merging.
> Bug fix joining class instances

- client/package-lock.json
- client/src/actions/actions.js
- client/src/api/api.js
- client/src/components/ClassCard/ClassCard.js
- client/src/components/Froms/CreateClass.js
- client/src/components/Froms/CreateTest.js
- client/src/components/Froms/Review.js
- client/src/components/Froms/TestForm.js
- client/src/views/main/Main.js
- server/controllers/classrooms.js
- server/routes/classrooms.js
#39 Missing package-lock.json in client directory
package-lock.json signifies what package should be used with this project else in future it can break due to packages upgrade. We should keep this file updated whenever any change is done in package.
> Add package lock in client directory for frontend

- client/src/actions/actions.js
- client/src/api/api.js
- client/src/components/ClassCard/ClassCard.js
- client/src/components/Froms/CreateClass.js
- client/src/components/Froms/CreateTest.js
- client/src/components/Froms/Review.js
- client/src/components/Froms/TestForm.js
- client/src/views/main/Main.js
- server/controllers/classrooms.js
- server/routes/classrooms.js
#6 
Added required feature of Classroom Edit and Delete.
> Class room edit and delete

- client/src/actions/actions.js
- client/src/components/ClassCard/ClassCard.js
- client/src/components/Navbar/Navbar.js
- client/src/views/main/Main.js
#28 Option for students to leave classrooms
With #37 we got solution to delete classroom - that same icon now represents 
option for leaving classroom
> Student leave classrooms

- client/src/actions/actions.js
Changed "Already joined th class" to "Already joined the class"
issue #59
> Typo in action.js

- client/src/actions/actions.js
- client/src/api/api.js
- client/src/components/TestCard/TestCard.js
- client/src/views/classroom/Classroom.js
- server/.env.example
Added  delete option in test issue #48
> Added Delete Functionality

- client/src/components/TestCard/TestCard.js
Added marks and duration in the test card
Closes: #62
Please let me know if any further changes are required.
> Test card enhancement

- server/package.json
Closes: #73 
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
| original screenshot | updated screenshot |
> Added start script

- server/package-lock.json
- server/package.json
- server/server.js
Closes: #85
I have uninstall the dependency body-parser and made changes to following lines in server.js
1. remove -> const bodyParser = require('body-parser');
2. app.use(bodyParser.urlencoded({ extended: true })); -> is replaced with -> app.use(express.urlencoded({ extended: true }));
3. app.use(bodyParser.json()); -> is replaced with -> app.use(express.json());
| original screenshot | updated screenshot |
> uninstall body-parser, make changes to server.js accordingly

- client/package-lock.json
- client/package.json
- client/src/components/Navbar/LoginFacebook.js
- client/src/components/Navbar/Logout.js
- client/src/components/Navbar/Navbar.js
This issue is related to adding more login feature to the platform (#47)
Closes: #47 
Added LOGIN WITH FACEBOOK feature using `react-login-facebook` library, where we need to provide an APPID to the Facebook login component and it automatically calls the Facebook APIs for the login info once the user is logged in we persist the user data onto local storage and on logging out we delete that data. 
| ![image](https://user-images.githubusercontent.com/54549066/111150744-7b0d2a80-85b4-11eb-931c-8431bb9d6e2e.png) | ![image](https://user-images.githubusercontent.com/54549066/111150654-5dd85c00-85b4-11eb-8700-6998890f2104.png) |
> Added LOGIN WITH FACEBOOK feature (#47)

- client/src/components/ClassCard/ClassCard.js
Fixed styling issues
Info about Issue or bug
As there is no limiting input size while creating a class,on big names class cards are not looking good as they got static(not responsive) css designs and also Delete button got hidden so one cannot able to delete their created class if their class name is big.
Closes: #90
Describe the changes you've made
I have made a function which truncates the string size if its beyond a range(As one of the mentors suggested in my previous PR)
- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
Original
Updated
> Updated ClassCard.js

- README.md
- This PR adds steps in README to run app using docker
Closes: #46 
Since there exists  docker-compose.yml file,we use docker-compose to spin up our containers and run the app.
> added docker support to readme file

- client/src/components/Navbar/Navbar.js
UI for the Navbar was not responsive(as instructed by the Project admin)
Closes: #90
i have created a function which truncates the large strings to make the ui responsive
- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
Original
(Project admin posted)
Updated
> Updated Navbar.js

- server/config/roles.js
- server/controllers/users.js
- server/models/users.model.js
- server/package-lock.json
- server/package.json
- server/routes/routes.js
- server/routes/users/users.js
Users are of two types teachers and students:
URL for signup :
User can logged in using username and password:
> User Schema and Routes #80

- client/src/components/Navbar/Navbar.js
- server/server.js
Now the current Class will be highlighted in a drawer when the user clicks on a particular class.
> Class highlight

- client/src/actions/actions.js
- client/src/views/App.js
- client/src/views/main/Main.js
Ok So I added a search box, now users just have to enter a value in the search box and the classes will dynamically change.
**I face one issue while doing this feature**: when the user enters the value inside the search box we have to change the state of classes and this is not possible to do in App.js. So I decided to directly call getClasses method inside **handlesearchChange** in **main.js** and please note **I also add 3rd argument which contain the user input value in getClasses method**
> search box added

- README.md
Fixed Typo in README.md
I have fixed typo in README.md of the repository.
> Update - README.md

- models/Classroom.js
- routes/api/classrooms.js
Closes: #121 
Deletes the corresponding tests to a classroom from the db if a classroom is deleted.
> implemented cascade deletion of tests after deletion of a classroom

- routes/api/tests.js
Test validations are performed only on the client side and not on the backend. Even though client side validations restrict every day users from sending in garbage or malicious data any one with the know hows of HTTP Requests can send a curl request directly to the end point with the data which could lead to unforeseen circumstances.
Closes: #146 
1. Check if rules have marks > 0
2. Calculate total marks based on rules and questions
3. Set test id of each question based on the id passed in the id field of request and not individual question
4. Validate if the test has a unique name
> Add backend validations

- client/public/index.html
- client/src/App.js
- client/src/actions/auth.js
- client/src/actions/types.js
- client/src/actions/ui.js
- client/src/components/dashboard/ClassCard.js
- client/src/components/dashboard/Dashboard.js
- client/src/components/layout/Navbar.js
- client/src/components/layout/NotFound.js
- client/src/components/layout/landing.module.css
- client/src/components/tests/QuestionForm.js
- client/src/components/tests/RulesForm.js
- client/src/components/tests/Testform.js
- client/src/components/themes/Theme.js
- client/src/reducers/index.js
- client/src/reducers/ui.js
- client/src/utils/themes.js
- models/User.js
- routes/api/users.js
- Apply Custom theming on platofrm
Closes: #149
As I describe in issue #149, I made a change in the frontend and backend both, 
You can see in file changes where I create UI reducer and UI action file and also /user/theme API endpoint for saving the selected user theme so that we can fetch there when user load.
Also, there is a feature to preview the theme by clicking on a theme that the user wants to change and this will apply to the whole page as a preview
There is one default theme which will be automatic saved when new user register.
Check below video
https://user-images.githubusercontent.com/53515714/113502124-d4c79b80-9547-11eb-9ed2-072e4a0a73bc.mp4
| original screenshot | updated screenshot |
> Custom Theme 

- routes/api/tests.js
Secure the API endpoints
Related: #151 
Added checks to prevent unauthorized test creation, also added checks to prevent users from sending a post request to add extra attempts or from attempting a test from a class they aren't enrolled in.
> Test API routes more secured now

- client/src/components/classroom/Classroom.js
- client/src/components/tests/CreateTest.js
- client/src/reducers/classroom.js
404 page was coming up while navigating between class , creating test
Closes:  #143
added  loading and error condition
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
Firstly the issue present in classroom.js was fixed by a simple loading condition, the second issue present in createTest.js was due to the GET_CLASSES was dispatching early than GET_CLASS as a result loading was diff into false but the property class remains the null  which leads to race condition of the class exist or it is still loading  (maybe in new commit it was vice versa as I clone repo 4 days back I am attaching a video to explain it )   
- [ x] My code follows the style guidelines of this …
> 404 page coming up Fix

- client/src/components/layout/Navbar.js
The problem in App Bar of Navbar
Closes: #167
I changed some lines of code in client/src/components/layout/Navbar.js
| ![image](https://user-images.githubusercontent.com/56081584/114874657-27436a80-9e1a-11eb-80ce-af58d2da3623.png) | ![image](https://user-images.githubusercontent.com/56081584/114874758-40e4b200-9e1a-11eb-9a7f-91ceb936f8b9.png) |
> fix: Problem in AppBar of Navbar

- client/package-lock.json
- client/src/components/layout/landing.module.css
- package-lock.json
- To add floating animation in the image of landing page.
Closes: #179
I have added  the floating animation in bookpen image in landingmodule.css file.
| 
original screenshot | 
updated screenshot |
>  Floating Animation added in image

- client/src/components/classroom/EditClass.js
- client/src/components/dashboard/handleFormError.js
- Updates are now reflecting to the form.
Closes: #182 
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
https://user-images.githubusercontent.com/75009990/116086444-73fe2f80-a6bd-11eb-852f-33fcad159639.mp4
> Update button rectified

- client/package-lock.json
- client/src/components/auth/Login.js
- client/src/components/auth/Register.js
- client/src/components/classroom/Classroom.js
- client/src/components/dashboard/Dashboard.js
- client/src/components/layout/Landing.js
- client/src/components/layout/landing.module.css
- To add the footer in all the pages
Closes: #184 
I have added a thin footer in all the pages of the website.
| original screenshot |
| updated screenshot |
> Updated footer in all pages

- client/package-lock.json
- client/src/components/layout/landing.module.css
- package-lock.json
- ITo fix responsiveness of landing page.
Closes: #180 
I have made the landing page responive. Footer to stick to  bottom.
| original screenshot |
updated screenshot |
> fixed responsiveness of the landing page

- client/package-lock.json
- client/src/components/auth/Login.css
- client/src/components/auth/Login.js
- client/src/components/auth/Register.js
- package-lock.json
- package.json
> signIn /sign up pages

- client/src/components/layout/Navbar.js
- Added login icon to login button
Closes: #189
> login icon added

- client/src/components/classroom/Classroom.js
- Subject Code Added to class template.
Closes: #181
| 
| 
|
> Subject Code Added

- client/src/components/layout/Navbar.js
- User friendly hovering effect on logout button.
Closes: #197 
I have added hovering effect to logot button.
| original screenshot | 
updated screenshot |
> Added hovering effect to logot button

- client/src/components/classroom/Classroom.js
-Changed the UI of copy Button
Closes: #187 
I have added color and icon
> UI to copy button 

- client/src/actions/auth.js
- client/src/components/auth/Login.js
- routes/api/auth.js
Closes: #203 
feature added for remember me
**exp without remember me**
**exp with remember me**
> Remember me feature added

- client/src/App.js
Closes: #216 
Removed the extra footer
| ![image](https://user-images.githubusercontent.com/70805691/119376784-fb00f080-bcd9-11eb-81e6-e4fb545bb5f7.png) | ![image](https://user-images.githubusercontent.com/70805691/119376822-08b67600-bcda-11eb-9e45-da130740ccd2.png) |
> removing the extra footer

- client/src/components/classroom/Classroom.js
- The link wasn't being copied onto the clipboard.
Closes: #215 
It was previously on local host but not on the main site. I tried something which is also working on local host, but I can't tell if it will work on the main site.
> Link being copied to the clipboard

- client/src/App.js
#195 
Closes: #195 
I have added the opacity to background image to make the content on it clear.
| 
| 
|
> opacity to background image

- client/.prettierrc
issue fixed #231 
| original screenshot | 
| updated screenshot |
> fixed prettier error

- README.md
Closes: #[issue number that will be closed through this PR]
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
| original screenshot | updated screenshot |
> Grammer changes
